export interface StateData {
  id: number;
  name: string;
  slug: string;
  status: 'recreational' | 'medical' | 'decriminalized' | 'illegal';
  possession_limits: string | null;
  age_requirement: string | null;
  purchase_rules: string | null;
  penalties: string | null;
  consumption_rules: string | null;
  dispensary_guide: string | null;
  travel_rules: string | null;
  subtitle: string | null;
  major_cities: string; // This will be the largest city for the guide
  medium_cities: string; // This will be the capital
  notable_areas: string; // This will be a placeholder
}

export const USA_STATE_DATA: StateData[] = [
  { id: 1, name: 'Alabama', slug: 'alabama', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. Decriminalization efforts failed.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Heart of Dixie: Strict cannabis laws.', major_cities: 'Birmingham', medium_cities: 'Montgomery', notable_areas: 'Mobile, Huntsville' },
  { id: 2, name: 'Alaska', slug: 'alaska', status: 'recreational', possession_limits: '1 oz (flower), 7g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land (e.g., national parks).', subtitle: 'The Last Frontier: Recreational cannabis is legal.', major_cities: 'Anchorage', medium_cities: 'Juneau', notable_areas: 'Fairbanks, Ketchikan' },
  { id: 3, name: 'Arizona', slug: 'arizona', status: 'recreational', possession_limits: '1 oz (flower), 5g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Grand Canyon State: Recreational cannabis is legal.', major_cities: 'Phoenix', medium_cities: 'Tucson', notable_areas: 'Tucson, Flagstaff' },
  { id: 4, name: 'Arkansas', slug: 'arkansas', status: 'medical', possession_limits: '2.5 oz every 14 days (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Natural State: Medical cannabis is legal.', major_cities: 'Little Rock', medium_cities: 'Fort Smith', notable_areas: 'Fayetteville, Hot Springs' },
  { id: 5, name: 'California', slug: 'california', status: 'recreational', possession_limits: '1 oz (flower), 8g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Golden State: Recreational cannabis is legal.', major_cities: 'Los Angeles', medium_cities: 'Sacramento', notable_areas: 'San Francisco, San Diego' },
  { id: 6, name: 'Colorado', slug: 'colorado', status: 'recreational', possession_limits: '1 oz (flower), 8g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Centennial State: Recreational cannabis is legal.', major_cities: 'Denver', medium_cities: 'Denver', notable_areas: 'Boulder, Aspen' },
  { id: 7, name: 'Connecticut', slug: 'connecticut', status: 'recreational', possession_limits: '1.5 oz (flower) on person, 5 oz at home.', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Constitution State: Recreational cannabis is legal.', major_cities: 'Bridgeport', medium_cities: 'Hartford', notable_areas: 'New Haven, Stamford' },
  { id: 8, name: 'Delaware', slug: 'delaware', status: 'recreational', possession_limits: '1 oz (flower).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only (sales starting late 2024).', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Sales are pending. Medical dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The First State: Recreational cannabis is legal.', major_cities: 'Wilmington', medium_cities: 'Dover', notable_areas: 'Newark, Rehoboth Beach' },
  { id: 9, name: 'Florida', slug: 'florida', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Sunshine State: Medical cannabis is legal.', major_cities: 'Jacksonville', medium_cities: 'Tallahassee', notable_areas: 'Miami, Orlando' },
  { id: 10, name: 'Georgia', slug: 'georgia', status: 'medical', possession_limits: '20 fl oz of low-THC oil (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed low-THC dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Low-THC oil dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Peach State: Low-THC oil is legal for medical use.', major_cities: 'Atlanta', medium_cities: 'Augusta', notable_areas: 'Savannah, Augusta' },
  { id: 11, name: 'Hawaii', slug: 'hawaii', status: 'medical', possession_limits: '4 oz every 15 days (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Decriminalized for small amounts (non-medical).', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Illegal to consume on federal land (e.g., national parks).', subtitle: 'The Aloha State: Medical cannabis is legal.', major_cities: 'Honolulu', medium_cities: 'Hilo', notable_areas: 'Maui, Kauai' },
  { id: 12, name: 'Idaho', slug: 'idaho', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. One of the strictest states.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Gem State: Strictly illegal.', major_cities: 'Boise', medium_cities: 'Meridian', notable_areas: 'Meridian, Nampa' },
  { id: 13, name: 'Illinois', slug: 'illinois', status: 'recreational', possession_limits: '30g (flower), 5g (concentrate) for residents.', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Prairie State: Recreational cannabis is legal.', major_cities: 'Chicago', medium_cities: 'Springfield', notable_areas: 'Aurora, Rockford' },
  { id: 14, name: 'Indiana', slug: 'indiana', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. Decriminalization efforts failed.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Hoosier State: Strictly illegal.', major_cities: 'Indianapolis', medium_cities: 'Fort Wayne', notable_areas: 'Fort Wayne, Evansville' },
  { id: 15, name: 'Iowa', slug: 'iowa', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Hawkeye State: Medical cannabis is legal.', major_cities: 'Des Moines', medium_cities: 'Cedar Rapids', notable_areas: 'Cedar Rapids, Davenport' },
  { id: 16, name: 'Kansas', slug: 'kansas', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. One of the strictest states.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Sunflower State: Strictly illegal.', major_cities: 'Wichita', medium_cities: 'Topeka', notable_areas: 'Overland Park, Kansas City' },
  { id: 17, name: 'Kentucky', slug: 'kentucky', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only (sales starting 2025).', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Sales are pending. No current dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Bluegrass State: Medical cannabis is legal (sales pending).', major_cities: 'Louisville', medium_cities: 'Frankfort', notable_areas: 'Lexington, Bowling Green' },
  { id: 18, name: 'Louisiana', slug: 'louisiana', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Decriminalized for small amounts (non-medical).', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Pelican State: Medical cannabis is legal.', major_cities: 'New Orleans', medium_cities: 'Baton Rouge', notable_areas: 'Shreveport, Lafayette' },
  { id: 19, name: 'Maine', slug: 'maine', status: 'recreational', possession_limits: '2.5 oz (flower), 5g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Pine Tree State: Recreational cannabis is legal.', major_cities: 'Portland', medium_cities: 'Augusta', notable_areas: 'Bangor, Lewiston' },
  { id: 20, name: 'Maryland', slug: 'maryland', status: 'recreational', possession_limits: '1.5 oz (flower), 12g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Old Line State: Recreational cannabis is legal.', major_cities: 'Baltimore', medium_cities: 'Annapolis', notable_areas: 'Columbia, Silver Spring' },
  { id: 21, name: 'Massachusetts', slug: 'massachusetts', status: 'recreational', possession_limits: '1 oz (flower) on person, 10 oz at home.', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Bay State: Recreational cannabis is legal.', major_cities: 'Boston', medium_cities: 'Worcester', notable_areas: 'Worcester, Springfield' },
  { id: 22, name: 'Michigan', slug: 'michigan', status: 'recreational', possession_limits: '2.5 oz (flower) on person, 10 oz at home.', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Great Lakes State: Recreational cannabis is legal.', major_cities: 'Detroit', medium_cities: 'Lansing', notable_areas: 'Grand Rapids, Ann Arbor' },
  { id: 23, name: 'Minnesota', slug: 'minnesota', status: 'recreational', possession_limits: '2 oz (flower), 8g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only (sales starting 2025).', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Sales are pending. Medical dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The North Star State: Recreational cannabis is legal (sales pending).', major_cities: 'Minneapolis', medium_cities: 'St. Paul', notable_areas: 'Rochester, Duluth' },
  { id: 24, name: 'Mississippi', slug: 'mississippi', status: 'medical', possession_limits: '3.5g of flower per day (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Magnolia State: Medical cannabis is legal.', major_cities: 'Jackson', medium_cities: 'Gulfport', notable_areas: 'Gulfport, Southaven' },
  { id: 25, name: 'Missouri', slug: 'missouri', status: 'recreational', possession_limits: '3 oz (flower).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Show Me State: Recreational cannabis is legal.', major_cities: 'Kansas City', medium_cities: 'Jefferson City', notable_areas: 'St. Louis, Springfield' },
  { id: 26, name: 'Montana', slug: 'montana', status: 'recreational', possession_limits: '1 oz (flower), 8g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land (e.g., national parks).', subtitle: 'The Treasure State: Recreational cannabis is legal.', major_cities: 'Billings', medium_cities: 'Helena', notable_areas: 'Missoula, Bozeman' },
  { id: 27, name: 'Nebraska', slug: 'nebraska', status: 'decriminalized', possession_limits: 'Decriminalized for up to 1 oz.', age_requirement: null, purchase_rules: null, penalties: 'Civil infraction for first offense.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Cornhusker State: Decriminalized.', major_cities: 'Omaha', medium_cities: 'Lincoln', notable_areas: 'Bellevue, Grand Island' },
  { id: 28, name: 'Nevada', slug: 'nevada', status: 'recreational', possession_limits: '1 oz (flower), 1/8 oz (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Silver State: Recreational cannabis is legal.', major_cities: 'Las Vegas', medium_cities: 'Carson City', notable_areas: 'Reno, Henderson' },
  { id: 29, name: 'New Hampshire', slug: 'new-hampshire', status: 'decriminalized', possession_limits: 'Decriminalized for up to 3/4 oz.', age_requirement: null, purchase_rules: null, penalties: 'Civil infraction for first offense.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Granite State: Decriminalized.', major_cities: 'Manchester', medium_cities: 'Concord', notable_areas: 'Nashua, Portsmouth' },
  { id: 30, name: 'New Jersey', slug: 'new-jersey', status: 'recreational', possession_limits: '6 oz (flower), 17g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Garden State: Recreational cannabis is legal.', major_cities: 'Newark', medium_cities: 'Trenton', notable_areas: 'Jersey City, Atlantic City' },
  { id: 31, name: 'New Mexico', slug: 'new-mexico', status: 'recreational', possession_limits: '2 oz (flower), 16g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Land of Enchantment: Recreational cannabis is legal.', major_cities: 'Albuquerque', medium_cities: 'Santa Fe', notable_areas: 'Las Cruces, Rio Rancho' },
  { id: 32, name: 'New York', slug: 'new-york', status: 'recreational', possession_limits: '3 oz (flower), 24g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Empire State: Recreational cannabis is legal.', major_cities: 'New York City', medium_cities: 'Albany', notable_areas: 'Buffalo, Rochester' },
  { id: 33, name: 'North Carolina', slug: 'north-carolina', status: 'medical', possession_limits: 'Low-THC oil only (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed low-THC dispensaries only.', penalties: 'Decriminalized for small amounts (non-medical).', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Low-THC oil dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Tar Heel State: Low-THC oil is legal for medical use.', major_cities: 'Charlotte', medium_cities: 'Raleigh', notable_areas: 'Greensboro, Durham' },
  { id: 34, name: 'North Dakota', slug: 'north-dakota', status: 'medical', possession_limits: '3 oz every 30 days (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Decriminalized for small amounts (non-medical).', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Peace Garden State: Medical cannabis is legal.', major_cities: 'Fargo', medium_cities: 'Bismarck', notable_areas: 'Grand Forks, Minot' },
  { id: 35, name: 'Ohio', slug: 'ohio', status: 'recreational', possession_limits: '2.5 oz (flower), 15g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Buckeye State: Recreational cannabis is legal.', major_cities: 'Columbus', medium_cities: 'Cleveland', notable_areas: 'Cleveland, Cincinnati' },
  { id: 36, name: 'Oklahoma', slug: 'oklahoma', status: 'medical', possession_limits: '3 oz (flower) on person, 8 oz at home (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Sooner State: Medical cannabis is legal.', major_cities: 'Oklahoma City', medium_cities: 'Tulsa', notable_areas: 'Tulsa, Norman' },
  { id: 37, name: 'Oregon', slug: 'oregon', status: 'recreational', possession_limits: '2 oz (flower) in public, 8 oz at home.', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Beaver State: Recreational cannabis is legal.', major_cities: 'Portland', medium_cities: 'Salem', notable_areas: 'Eugene, Bend' },
  { id: 38, name: 'Pennsylvania', slug: 'pennsylvania', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Decriminalized for small amounts (non-medical).', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Keystone State: Medical cannabis is legal.', major_cities: 'Philadelphia', medium_cities: 'Harrisburg', notable_areas: 'Pittsburgh, Allentown' },
  { id: 39, name: 'Rhode Island', slug: 'rhode-island', status: 'recreational', possession_limits: '1 oz (flower) on person, 10 oz at home.', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Ocean State: Recreational cannabis is legal.', major_cities: 'Providence', medium_cities: 'Warwick', notable_areas: 'Warwick, Cranston' },
  { id: 40, name: 'South Carolina', slug: 'south-carolina', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. No medical or recreational use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Palmetto State: Strictly illegal.', major_cities: 'Columbia', medium_cities: 'Charleston', notable_areas: 'Charleston, North Charleston' },
  { id: 41, name: 'South Dakota', slug: 'south-dakota', status: 'medical', possession_limits: '3 oz (flower) (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'Mount Rushmore State: Medical cannabis is legal.', major_cities: 'Sioux Falls', medium_cities: 'Pierre', notable_areas: 'Rapid City, Aberdeen' },
  { id: 42, name: 'Tennessee', slug: 'tennessee', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. Decriminalization efforts failed.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Volunteer State: Strictly illegal.', major_cities: 'Memphis', medium_cities: 'Nashville', notable_areas: 'Knoxville, Chattanooga' },
  { id: 43, name: 'Texas', slug: 'texas', status: 'medical', possession_limits: 'Low-THC oil only (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed low-THC dispensaries only.', penalties: 'Decriminalized for small amounts (non-medical).', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Low-THC oil dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Lone Star State: Low-THC oil is legal for medical use.', major_cities: 'Houston', medium_cities: 'Austin', notable_areas: 'Dallas, San Antonio' },
  { id: 44, name: 'Utah', slug: 'utah', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Beehive State: Medical cannabis is legal.', major_cities: 'Salt Lake City', medium_cities: 'West Valley City', notable_areas: 'West Valley City, Provo' },
  { id: 45, name: 'Vermont', slug: 'vermont', status: 'recreational', possession_limits: '1 oz (flower), 5g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Green Mountain State: Recreational cannabis is legal.', major_cities: 'Burlington', medium_cities: 'Montpelier', notable_areas: 'Essex, Rutland' },
  { id: 46, name: 'Virginia', slug: 'virginia', status: 'decriminalized', possession_limits: 'Decriminalized for up to 1 oz.', age_requirement: null, purchase_rules: null, penalties: 'Civil infraction for first offense.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Old Dominion: Decriminalized.', major_cities: 'Virginia Beach', medium_cities: 'Richmond', notable_areas: 'Norfolk, Chesapeake' },
  { id: 47, name: 'Washington', slug: 'washington', status: 'recreational', possession_limits: '1 oz (flower), 7g (concentrate).', age_requirement: '21+', purchase_rules: 'Licensed dispensaries only.', penalties: 'Minor offenses are civil fines.', consumption_rules: 'Private property only. Public consumption is illegal.', dispensary_guide: 'Legal recreational dispensaries are open.', travel_rules: 'Illegal to consume on federal land.', subtitle: 'The Evergreen State: Recreational cannabis is legal.', major_cities: 'Seattle', medium_cities: 'Olympia', notable_areas: 'Spokane, Tacoma' },
  { id: 48, name: 'West Virginia', slug: 'west-virginia', status: 'medical', possession_limits: 'Varies by doctor recommendation (medical).', age_requirement: '18+ with medical card.', purchase_rules: 'Licensed medical dispensaries only.', penalties: 'Strict penalties for non-medical use.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'Medical dispensaries are open.', travel_rules: 'Medical card not recognized for non-residents.', subtitle: 'The Mountain State: Medical cannabis is legal.', major_cities: 'Charleston', medium_cities: 'Huntington', notable_areas: 'Huntington, Morgantown' },
  { id: 49, name: 'Wisconsin', slug: 'wisconsin', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. Decriminalization efforts failed.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Badger State: Strictly illegal.', major_cities: 'Milwaukee', medium_cities: 'Madison', notable_areas: 'Green Bay, Kenosha' },
  { id: 50, name: 'Wyoming', slug: 'wyoming', status: 'illegal', possession_limits: 'Any amount is a misdemeanor/felony.', age_requirement: null, purchase_rules: null, penalties: 'Strict penalties. One of the strictest states.', consumption_rules: 'Strictly prohibited in public.', dispensary_guide: 'No legal dispensaries.', travel_rules: 'Do not cross state lines with cannabis.', subtitle: 'The Equality State: Strictly illegal.', major_cities: 'Cheyenne', medium_cities: 'Casper', notable_areas: 'Casper, Laramie' },
];
