-- SQL Migration to populate global country laws
-- Date: 2025-12-18
-- Source: WorldGuide.tsx data

INSERT INTO public.countries (name, slug, region, status, possession_limits, airport_rules, consumption_notes, penalties)
VALUES
-- North America
('Canada', 'canada', 'North America', 'recreational', '30 g public / unlimited home', '30 g domestic only (Illegal international)', 'Gov stores only; ID required (18/19+)', 'Strict driving laws apply.'),
('United States', 'united-states', 'North America', 'medical', 'Varies by state (Illegal Federally)', 'Federal prohibition (TSA)', 'Check state laws', 'Interstate transport is a Federal Crime'),
('Mexico', 'mexico', 'North America', 'decriminalized', 'Small amounts tolerated (<5g)', 'Zero tolerance', 'Technical tolerance, but police extortion is common.', 'Police often target tourists for bribes.'),

-- Central America
('Costa Rica', 'costa-rica', 'Central America', 'decriminalized', 'No specific amount defined', 'Zero tolerance', 'Personal consumption in private is tolerated.', 'Selling is a serious crime.'),
('Panama', 'panama', 'Central America', 'medical', 'Prison sentences for recreational use', 'Zero tolerance', 'Strict laws. Recreational use is illegal.', 'Recreational use remains a crime with potential jail time.'),
('Belize', 'belize', 'Central America', 'decriminalized', 'Up to 10g (Private property ONLY)', 'Zero tolerance', 'Possession legal in private lodgings.', 'Illegal in public.'),
('Guatemala', 'guatemala', 'Central America', 'illegal', 'Prison sentences (4 months - 2 years)', 'Zero tolerance', 'High risk.', 'Penalties are harsh even for consumption.'),
('El Salvador', 'el-salvador', 'Central America', 'illegal', 'Arrest and indefinite detention', 'Zero tolerance', 'WARNING: State of Exception.', 'Risk of arbitrary arrest.'),
('Honduras', 'honduras', 'Central America', 'illegal', 'Prison sentences', 'Zero tolerance', 'Strongly discouraged.', 'Strict drug laws.'),
('Nicaragua', 'nicaragua', 'Central America', 'illegal', 'Prison sentences', 'Zero tolerance', 'High caution.', 'Severe penalties.'),

-- Europe
('Netherlands', 'netherlands', 'Europe', 'decriminalized', '5 g tolerated', 'Do not transport', 'Coffee-shop weed is potent.', 'Sale tolerated under strict conditions.'),
('Germany', 'germany', 'Europe', 'recreational', '25 g public / 50 g home', 'Domestic only (Risk)', 'Possession legal, but BUYING is illegal for tourists.', 'Social Clubs for residents only.'),
('Spain', 'spain', 'Europe', 'decriminalized', 'Private areas OK', 'Do not transport', 'Join private cannabis club', 'Public use fined.'),
('Italy', 'italy', 'Europe', 'decriminalized', 'Small home grow tolerated', 'Zero tolerance', 'CBD legal; THC illegal.', 'Administrative fines.'),
('Portugal', 'portugal', 'Europe', 'decriminalized', '25 g civil fine', 'Do not transport', 'Police will confiscate.', 'All drugs decriminalised 2001.'),
('Switzerland', 'switzerland', 'Europe', 'decriminalized', '10 g civil fine', 'Do not transport', 'Low-THC (<1%) sold legally.', 'High-THC trials in some cities.'),
('Austria', 'austria', 'Europe', 'decriminalized', 'Purchase seeds & hemp', 'Do not transport', 'Enjoy Alps; herb secondary.', 'High THC is illegal.'),
('Czech Republic', 'czech-republic', 'Europe', 'decriminalized', '15 g civil fine', 'Do not transport', 'Tolerated but technically illegal to sell.', 'Medical cannabis is legal.'),
('Malta', 'malta', 'Europe', 'recreational', '7 g home / 3.5 g public', 'Do not transport', 'Associations are Residents Only.', 'Public consumption is fined.'),
('Luxembourg', 'luxembourg', 'Europe', 'recreational', '3 g home grow', 'Do not transport', 'Residents only.', 'Sales strictly illegal.'),
('Belgium', 'belgium', 'Europe', 'decriminalized', '3 g civil fine', 'Do not transport', 'Enjoy waffles.', 'Lowest prosecution priority.'),
('France', 'france', 'Europe', 'illegal', 'Fines / Police custody', 'Zero tolerance', 'Strictly illegal.', 'On-the-spot fines (€200).'),
('United Kingdom', 'uk', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only via specialist doctor.', 'Recreational use is illegal (Class B).'),
('Ireland', 'ireland', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Strictly illegal.'),
('Denmark', 'denmark', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Christiania crackdown.', 'Medical cannabis legal.'),
('Finland', 'finland', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Norway', 'norway', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Sweden', 'sweden', 'Europe', 'illegal', 'Strict Penalties', 'Zero tolerance', 'Zero tolerance culture.', 'Strict drug laws.'),
('Iceland', 'iceland', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Poland', 'poland', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Estonia', 'estonia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Latvia', 'latvia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Lithuania', 'lithuania', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Slovenia', 'slovenia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Slovakia', 'slovakia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Hungary', 'hungary', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Croatia', 'croatia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Serbia', 'serbia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Bosnia & Herzegovina', 'bosnia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Montenegro', 'montenegro', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('North Macedonia', 'north-macedonia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Albania', 'albania', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Greece', 'greece', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Bulgaria', 'bulgaria', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Romania', 'romania', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Moldova', 'moldova', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Ukraine', 'ukraine', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'War-time caution.'),
('Russia', 'russia', 'Europe', 'illegal', 'Criminal offence', 'Zero tolerance', 'WARNING: Severe penalties.', 'Political hostages possible.'),
('Belarus', 'belarus', 'Europe', 'illegal', 'Criminal offence', 'Zero tolerance', 'Authoritarian.', 'Possession criminalised.'),
('Turkey', 'turkey', 'Europe', 'illegal', 'Strict penalites', 'Zero tolerance', 'Strict laws.', 'Medical heavily restricted.'),
('Cyprus', 'cyprus', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Georgia', 'georgia', 'Europe', 'decriminalized', 'Small amounts tolerated', 'Zero tolerance', 'Private use decriminalized.', 'Purchase/sale is illegal.'),
('Armenia', 'armenia', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Azerbaijan', 'azerbaijan', 'Europe', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),

-- South America
('Uruguay', 'uruguay', 'South America', 'recreational', '40 g monthly (residents)', 'Transport prohibited', 'Tourists cannot purchase.', 'World’s first full legalisation.'),
('Argentina', 'argentina', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Chile', 'chile', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Colombia', 'colombia', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Brazil', 'brazil', 'South America', 'decriminalized', 'Decriminalized (40g)', 'Zero tolerance', 'Personal use decriminalized.', 'Selling is a felony.'),
('Peru', 'peru', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Venezuela', 'venezuela', 'South America', 'illegal', 'Criminal offence', 'Zero tolerance', 'Avoid travel.', 'Possession criminalised.'),
('Ecuador', 'ecuador', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Bolivia', 'bolivia', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Paraguay', 'paraguay', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Guyana', 'guyana', 'South America', 'illegal', 'Criminal offence', 'Zero tolerance', 'Jungle frontier.', 'Possession criminalised.'),
('Suriname', 'suriname', 'South America', 'illegal', 'Criminal offence', 'Zero tolerance', 'Rainforest.', 'Possession criminalised.'),
('French Guiana', 'french-guiana', 'South America', 'medical', 'Medical prescription only', 'Zero tolerance', 'EU Amazon.', 'Recreational prohibited.'),

-- Caribbean
('Jamaica', 'jamaica', 'Caribbean', 'decriminalized', 'Small amounts tolerated', 'Do not transport', 'Enjoy reggae.', 'Decriminalised 2015.'),
('Barbados', 'barbados', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Trinidad & Tobago', 'trinidad-tobago', 'Caribbean', 'decriminalized', '30 g civil fine', 'Zero tolerance', 'Enjoy carnival.', 'Decriminalised 2019.'),
('Bahamas', 'bahamas', 'Caribbean', 'illegal', 'Criminal offence', 'Zero tolerance', 'Island paradise.', 'Possession criminalised.'),
('Cuba', 'cuba', 'Caribbean', 'illegal', 'Criminal offence', 'Zero tolerance', 'Socialist island.', 'Possession criminalised.'),
('Dominican Republic', 'dominican-republic', 'Caribbean', 'illegal', 'Criminal offence', 'Zero tolerance', 'Resort island.', 'Possession criminalised.'),
('Haiti', 'haiti', 'Caribbean', 'illegal', 'Criminal offence', 'Zero tolerance', 'Crisis zone.', 'Possession criminalised.'),
('Puerto Rico', 'puerto-rico', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('US Virgin Islands', 'us-virgin-islands', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('British Virgin Islands', 'british-virgin-islands', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Anguilla', 'anguilla', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('St Maarten', 'st-maarten', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('St Kitts & Nevis', 'st-kitts-nevis', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Antigua & Barbuda', 'antigua-barbuda', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Dominica', 'dominica', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Grenada', 'grenada', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('St Lucia', 'st-lucia', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('St Vincent & the Grenadines', 'st-vincent-grenadines', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Bermuda', 'bermuda', 'Caribbean', 'recreational', '7 g possession legal', 'Import prohibited', 'Residents only.', 'Legalised 2022.'),
('Cayman Islands', 'cayman-islands', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Turks & Caicos', 'turks-caicos', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Aruba', 'aruba', 'Caribbean', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Curaçao', 'curacao', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Bonaire', 'bonaire', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Sint Eustatius', 'sint-eustatius', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Saba', 'saba', 'Caribbean', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),

-- Asia
('Thailand', 'thailand', 'Asia', 'medical', 'Medical prescription required (2025)', 'Illegal to import/export', 'WARNING: Recreational era ending.', 'Decriminalized in 2022, tightening in 2025.'),
('Singapore', 'singapore', 'Asia', 'illegal', 'Caning & Long Prison Terms', 'Zero tolerance (Death penalty risk)', 'Death penalty for trafficking.', 'Mandatory death penalty for >500g.'),
('Malaysia', 'malaysia', 'Asia', 'illegal', 'Severe prison / Caning', 'Zero tolerance', 'Death penalty risk.', 'Strictly illegal.'),
('Indonesia', 'indonesia', 'Asia', 'illegal', 'Prison / Deportation', 'Zero tolerance (Death penalty risk)', 'Severe penalties (Bali included).', 'Strictly illegal.'),
('Philippines', 'philippines', 'Asia', 'illegal', 'Life imprisonment for large amounts', 'Zero tolerance', 'Severe penalties.', 'Strictly illegal.'),
('Vietnam', 'vietnam', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Death penalty for trafficking.', 'Strictly illegal.'),
('Laos', 'laos', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Cambodia', 'cambodia', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Myanmar', 'myanmar', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Civil-war zone.', 'Possession criminalised.'),
('China', 'china', 'Asia', 'illegal', 'Detention / Deportation', 'Zero tolerance', 'Random drug tests possible.', 'Strictly illegal.'),
('Japan', 'japan', 'Asia', 'illegal', 'Prison (up to 5 years)', 'Zero tolerance', 'Zero tolerance culture.', 'Strictly illegal.'),
('South Korea', 'south-korea', 'Asia', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('North Korea', 'north-korea', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Unknown regime.', 'Regime opaque.'),
('Mongolia', 'mongolia', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Taiwan', 'taiwan', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Hong Kong', 'hong-kong', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Macau', 'macau', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('India', 'india', 'Asia', 'medical', 'State dependent (Bhang tolerated)', 'Zero tolerance', 'Flower illegal; Bhang legal in some states.', 'National law bans flower and resin.'),
('Pakistan', 'pakistan', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Bangladesh', 'bangladesh', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Sri Lanka', 'sri-lanka', 'Asia', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Nepal', 'nepal', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Hash history.', 'Possession criminalised.'),
('Bhutan', 'bhutan', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Strongly discouraged.', 'Possession criminalised.'),
('Israel', 'israel', 'Asia', 'medical', '30 g public / 2 oz home', 'Zero tolerance', 'Medical only.', 'Strict laws.'),
('Lebanon', 'lebanon', 'Asia', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Economic crisis focus.'),
('Palestine', 'palestine', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Conflict zone.', 'Possession criminalised.'),
('Jordan', 'jordan', 'Asia', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Saudi Arabia', 'saudi-arabia', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Extreme penalties (Death/Lashes).', 'Strictly illegal.'),
('United Arab Emirates', 'uae', 'Asia', 'illegal', '4+ years prison / Deportation', 'Zero tolerance', 'THC in blood counts as possession.', 'Zero tolerance.'),
('Qatar', 'qatar', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Severe penalties.', 'Strictly illegal.'),
('Kuwait', 'kuwait', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Harsh penalties.', 'Strictly illegal.'),
('Bahrain', 'bahrain', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Island kingdom.', 'Strictly illegal.'),
('Oman', 'oman', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Desert sultanate.', 'Strictly illegal.'),
('Yemen', 'yemen', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'War zone.', 'Possession criminalised.'),
('Brunei', 'brunei', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Death-penalty risk.', 'Strictly illegal.'),
('East Timor', 'east-timor', 'Asia', 'illegal', 'Criminal offence', 'Zero tolerance', 'Developing nation.', 'Possession criminalised.'),

-- Africa
('South Africa', 'south-africa', 'Africa', 'decriminalized', 'Private use & grow OK', 'Transport prohibited', 'Private homes only.', 'Constitutional Court ruling.'),
('Zimbabwe', 'zimbabwe', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Lesotho', 'lesotho', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'First African nation to legalise medical.'),
('Morocco', 'morocco', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Tolerated in Rif.', 'Strictly illegal elsewhere.'),
('Ghana', 'ghana', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Nigeria', 'nigeria', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Harsh penalties.', 'Possession criminalised.'),
('Egypt', 'egypt', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Harsh penalties.', 'Possession criminalised.'),
('Ethiopia', 'ethiopia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Coffee over cannabis.', 'Possession criminalised.'),
('Kenya', 'kenya', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Safari over smoke.', 'Possession criminalised.'),
('Uganda', 'uganda', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Tanzania', 'tanzania', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Zanzibar beaches.', 'Possession criminalised.'),
('Zambia', 'zambia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Victoria Falls.', 'Possession criminalised.'),
('Botswana', 'botswana', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Okavango Delta.', 'Possession criminalised.'),
('Namibia', 'namibia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Desert vastness.', 'Possession criminalised.'),
('Angola', 'angola', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Oil-rich.', 'Possession criminalised.'),
('Mozambique', 'mozambique', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Indian-Ocean beaches.', 'Possession criminalised.'),
('Malawi', 'malawi', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Lake Malawi.', 'Possession criminalised.'),
('Rwanda', 'rwanda', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Gorilla trekking.', 'Possession criminalised.'),
('Burundi', 'burundi', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Crisis zone.', 'Possession criminalised.'),
('Djibouti', 'djibouti', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Military hub.', 'Possession criminalised.'),
('Eritrea', 'eritrea', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Closed nation.', 'Possession criminalised.'),
('Somalia', 'somalia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'War zone.', 'Possession criminalised.'),
('Sudan', 'sudan', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Conflict zone.', 'Possession criminalised.'),
('Libya', 'libya', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'War zone.', 'Possession criminalised.'),
('Tunisia', 'tunisia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Mediterranean.', 'Possession criminalised.'),
('Algeria', 'algeria', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Sahara desert.', 'Possession criminalised.'),
('Mauritania', 'mauritania', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Sahara vast.', 'Possession criminalised.'),
('Mali', 'mali', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Conflict zone.', 'Possession criminalised.'),
('Burkina Faso', 'burkina-faso', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Crisis zone.', 'Possession criminalised.'),
('Niger', 'niger', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Sahara-Sahel.', 'Possession criminalised.'),
('Chad', 'chad', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Desert vast.', 'Possession criminalised.'),
('Central African Republic', 'central-african-republic', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'War zone.', 'Possession criminalised.'),
('Cameroon', 'cameroon', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Bilingual nation.', 'Possession criminalised.'),
('Equatorial Guinea', 'equatorial-guinea', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Oil-rich.', 'Possession criminalised.'),
('Gabon', 'gabon', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Rainforest.', 'Possession criminalised.'),
('Republic of the Congo', 'republic-congo', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Rainforest.', 'Possession criminalised.'),
('Democratic Republic of the Congo', 'democratic-republic-congo', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Conflict zone.', 'Possession criminalised.'),
('Benin', 'benin', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Voodoo heartland.', 'Possession criminalised.'),
('Togo', 'togo', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Narrow nation.', 'Possession criminalised.'),
('Ivory Coast', 'ivory-coast', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Cocoa coast.', 'Possession criminalised.'),
('Liberia', 'liberia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'War recovery.', 'Possession criminalised.'),
('Sierra Leone', 'sierra-leone', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Diamond coast.', 'Possession criminalised.'),
('Guinea', 'guinea', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Bauxite rich.', 'Possession criminalised.'),
('Guinea-Bissau', 'guinea-bissau', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Cashew coast.', 'Possession criminalised.'),
('Gambia', 'gambia', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'River nation.', 'Possession criminalised.'),
('Senegal', 'senegal', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Teranga hospitality.', 'Possession criminalised.'),
('Cape Verde', 'cape-verde', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Atlantic islands.', 'Possession criminalised.'),
('São Tomé & Príncipe', 'sao-tome-principe', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Chocolate islands.', 'Possession criminalised.'),
('Seychelles', 'seychelles', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Mauritius', 'mauritius', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Comoros', 'comoros', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Perfume islands.', 'Possession criminalised.'),
('Madagascar', 'madagascar', 'Africa', 'illegal', 'Criminal offence', 'Zero tolerance', 'Lemur island.', 'Possession criminalised.'),
('Réunion', 'reunion', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'French island.'),
('Mayotte', 'mayotte', 'Africa', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'French island.'),

-- Oceania
('Australia', 'australia', 'Oceania', 'medical', 'Medical only (Except ACT)', 'Zero tolerance', 'Medical only.', 'ACT (Canberra) allows personal grow/use.'),
('New Zealand', 'new-zealand', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Referendum failed.'),
('Fiji', 'fiji', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Papua New Guinea', 'papua-new-guinea', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Samoa', 'samoa', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Tonga', 'tonga', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Hawaii (USA)', 'hawaii', 'Oceania', 'recreational', '1 oz public / 10 oz home', 'Inter-island transport OK', 'Dispensaries on islands.', 'Legal since 2020.'),
('Solomon Islands', 'solomon-islands', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Vanuatu', 'vanuatu', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Kiribati', 'kiribati', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Tuvalu', 'tuvalu', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Nauru', 'nauru', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Palau', 'palau', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Marshall Islands', 'marshall-islands', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Federated States of Micronesia', 'federated-states-micronesia', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('New Caledonia', 'new-caledonia', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('French Polynesia', 'french-polynesia', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Wallis & Futuna', 'wallis-futuna', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Norfolk Island', 'norfolk-island', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Cocos Islands', 'cocos-islands', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Christmas Island', 'christmas-island', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Pitcairn Islands', 'pitcairn-islands', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Tokelau', 'tokelau', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Niue', 'niue', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.'),
('Cook Islands', 'cook-islands', 'Oceania', 'medical', 'Medical prescription only', 'Zero tolerance', 'Medical only.', 'Recreational prohibited.')

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  status = EXCLUDED.status,
  possession_limits = EXCLUDED.possession_limits,
  airport_rules = EXCLUDED.airport_rules,
  consumption_notes = EXCLUDED.consumption_notes,
  penalties = EXCLUDED.penalties,
  last_updated = now();
